title: Mykhaylo Filip
description: <a href="/posts" class="btn">Posts</a> <a href="/awards" class="btn">Awards</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
site_favicon: favicon.ico
