title: Mykhaylo Filip
description:  >
  <div class="button-group">
    <a href="/posts" class="btn">Posts</a>
    <a href="/awards" class="btn">Awards</a>
    <a href="/about" class="btn">About</a>
  </div>
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
site_favicon: favicon.ico
